# This workflow is written specifically for Jam3/nextjs-boilerplate
# It uploads all contents inside the ./out/ folder generated on build:prod:static process to a AWS S3 account

name: Github Action S3 Deploy

on:
  workflow_call:
    inputs:
      CI_ENV:
        required: true
        type: string
      WEBSITE_SITE_URL:
        required: true
        type: string
      S3_ORIGIN_BUCKET:
        required: true
        type: string
      CLOUDFRONT_DISTRIBUTION_ID:
        required: true
        type: string
      AWS_DEFAULT_REGION:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build NextJS static site
        run: ./.github/scripts/build.sh
        shell: bash
        env:
          CI_ENV: ${{ inputs.CI_ENV }}
          WEBSITE_SITE_URL: ${{ inputs.WEBSITE_SITE_URL }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: S3 Deploy
        run: ./.github/scripts/deploy.sh
        shell: bash
        env:
          S3_ORIGIN_BUCKET: ${{ inputs.S3_ORIGIN_BUCKET }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ inputs.CLOUDFRONT_DISTRIBUTION_ID }}
          AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION }}
