ls:
  .js: kebab-case | pointcase
  .ts: kebab-case | pointcase
  .d.ts: kebab-case
  .config.js: kebab-case
  src:
    assets:
      .png: kebab-case | regex:[^+]
      .jpg: kebab-case | regex:[^+]
      .jpeg: kebab-case | regex:[^+]
      .webp: kebab-case | regex:[^+]
      .svg: kebab-case | regex:[^+]
      .mp4: kebab-case | regex:[^+]
      .webm: kebab-case | regex:[^+]
    components:
      .js: PascalCase
      .tsx: PascalCase
      .stories.js: PascalCase
      .stories.tsx: PascalCase
      .svg: kebab-case
    pages:
      .js: kebab-case | regex:^_[a-z-.]* | regex:^\[\w*\] #regex for kebab-case with preceeding underscore or [] for dynamic routing
      .tsx: kebab-case | regex:^_[a-z-.]* | regex:^\[\w*\] #regex for kebab-case with preceeding underscore or [] for dynamic routing
  scripts:
    templates:
      .js: PascalCase
      .stories.js: PascalCase

ignore:
  - node_modules
  - .next
  - out
