ls:
  .js: kebab-case | pointcase
  .ts: kebab-case | pointcase
  .d.ts: kebab-case
  .config.js: kebab-case
  src:
    assets:
      .png: kebab-case | regex:[^+]
      .jpg: kebab-case | regex:[^+]
      .jpeg: kebab-case | regex:[^+]
      .webp: kebab-case | regex:[^+]
      .svg: kebab-case | regex:[^+]
      .mp4: kebab-case | regex:[^+]
      .webm: kebab-case | regex:[^+]
    components:
      .js: PascalCase | regex:[index]+
      .ts: PascalCase | regex:[index]+
      .tsx: PascalCase | regex:[index]+
      .scss: PascalCase
      .view.tsx: PascalCase
      .module.scss: PascalCase
      .stories.js: PascalCase
      .stories.tsx: PascalCase
      .controller.tsx: PascalCase
      .crossflow.tsx: PascalCase
      .presence.tsx: PascalCase
      .context.ts: PascalCase
    data:
      .js: kebab-case
      .ts: kebab-case
      .json: kebab-case
    hooks:
      .js: kebab-case
      .ts: kebab-case
    pages:
      .js: kebab-case | regex:^_[a-z-.]* | regex:^\[\w*\] #regex for kebab-case with preceeding underscore or [] for dynamic routing
      .tsx: kebab-case | regex:^_[a-z-.]* | regex:^\[\w*\] #regex for kebab-case with preceeding underscore or [] for dynamic routing
    services:
      .service.js: kebab-case
      .service.ts: kebab-case
    styles:
      .scss: kebab-case
      .module.scss: kebab-case
    utils:
      .js: kebab-case
      .ts: kebab-case
      .d.ts: kebab-case
    svgs:
      .svg: PascalCase
  scripts:
    templates:
      .js: PascalCase
      .stories.js: PascalCase

ignore:
  - node_modules
  - .next
  - out
