version: 2.1

workflows:
  version: 2
  pull-requests:
    jobs:
      - setup:
          filters:
            branches:
              ignore:
                - develop
                - staging
                - main
      - linters:
          name: linters
          requires:
            - setup
      - secrets-key-detection:
          requires:
            - setup
      - build:
          requires:
            - linters
            - secrets-key-detection
      - html-validator:
          requires:
            - build
          s3_origin_bucket: $S3_ORIGIN_DEV
      - preview-environment:
          context: GITHUB_CREDENTIALS
          requires:
            - build
          env_suffix: '_DEV'
