#!/bin/bash

if [ "${CIRCLE_BRANCH}" == "develop" ]
then
  export NODE_ENV=development
  export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_DEV}
  export AWS_ACCESS_KEY_SECRET=${AWS_ACCESS_KEY_SECRET_DEV}
  export S3_ORIGIN_BUCKET=${S3_ORIGIN_BUCKET_DEV}
  export CLOUDFRONT_DISTRIBUTION_ID=${CLOUDFRONT_DISTRIBUTION_ID_DEV}
elif [ "${CIRCLE_BRANCH}" == "staging" ]
then
  export NODE_ENV=staging
  export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_STAGE}
  export AWS_ACCESS_KEY_SECRET=${AWS_ACCESS_KEY_SECRET_STAGE}
  export S3_ORIGIN_BUCKET=${S3_ORIGIN_BUCKET_STAGE}
  export CLOUDFRONT_DISTRIBUTION_ID=${CLOUDFRONT_DISTRIBUTION_ID_STAGE}
elif [ "${CIRCLE_BRANCH}" == "main" ]
then
  export NODE_ENV=production
  export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_PROD}
  export AWS_ACCESS_KEY_SECRET=${AWS_ACCESS_KEY_SECRET_PROD}
  export S3_ORIGIN_BUCKET=${S3_ORIGIN_BUCKET_PROD}
  export CLOUDFRONT_DISTRIBUTION_ID=${CLOUDFRONT_DISTRIBUTION_ID_PROD}
fi

echo "Sucessfull build for environment: ${NODE_ENV}"

exit 0
