version: 2.1

jobs:
  html-validator:
    docker:
      - image: python:3.6-stretch
    steps:
      - run:
          name: install Java
          command: apt-get update && apt-get install -y openjdk-8-jre
      - run:
          name: install
          command: pip install html5validator
      - checkout
      - run: mkdir /html5validator
      - attach_workspace:
          at: .
      - run:
          name: validate html
          command: html5validator --root out --format json > /html5validator/report.json
      - store_artifacts:
          path: /html5validator
          destination: html5validator-report
