version: 2.1

jobs:
  html-validator:
    docker:
      - image: python:3.6-stretch

    parameters:
      s3_origin_bucket:
        description: 'S3 origin bucket name'
        default: 'jam3-s3-example-name'
        type: string

    steps:
      - run:
          name: install Java
          command: apt-get update && apt-get install -y openjdk-8-jre
      - run:
          name: install
          command: pip install html5validator
      - checkout
      - run: mkdir /html5validator
      - attach_workspace:
          at: .
      - run:
          name: validate html
          command: html5validator --root out --format json > /html5validator/report.json | cat
      - run:
          command: aws s3 sync /html5validator s3://<< parameters.s3_origin_bucket >>/report/html
          when: always
      - store_artifacts:
          path: /html5validator
          destination: html5validator-report
