version: 2.1

jobs:
  mozilla-observatory:
    docker:
      - image: mozilla/observatory-cli

    parameters:
      environment_domain:
        description: 'Domain'
        default: 'dev.test.cloud.jam3.net'
        type: string
      target_path:
        description: 'Paths to test, ex "/test"'
        default: '/'
        type: string
      basic_auth_token:
        description: 'basic auth token'
        type: string
        default: ''

    steps:
      - run: echo "https://<< parameters.environment_domain >><< parameters.target_path >>?token=<< parameters.basic_auth_token >>"
      - run: observatory << parameters.environment_domain >><< parameters.target_path >>?token=<< parameters.basic_auth_token >> --format report --rescan --min-grade A
      - run: echo "Review the results in https://observatory.mozilla.org/analyze/${PRODUCTION_URL}"
