version: 2.1

jobs:
  webhint:
    # TODO
    # 1. Create parameters
    # 2. Integrate webhint into the generator (so it can be cached), or use a docker with webhint
    # 3. Create .hintrc and exclude some things
    # 4. Upload report to S3
    docker:
      - image: cimg/node:14.19.1-browsers

    parameters:
      environment_domain:
        description: 'Domain'
        default: 'dev.test.cloud.jam3.net'
        type: string
      target_path:
        description: 'Paths to test, ex "/test"'
        default: '/'
        type: string
      basic_auth_token:
        description: 'basic auth token'
        type: string
        default: ''

    steps:
      - checkout
      - run: npm install hint --no-save
      - run: node node_modules/hint/dist/src/bin/hint.js https://<< parameters.environment_domain >><< parameters.target_path >>?token=<< parameters.basic_auth_token >>
